function scr_init_sprite_array(){
var _ = [
 spr_card_back,
 
 spr_clubs_ace,
 spr_clubs_2,
 spr_clubs_3,
 spr_clubs_4,
 spr_clubs_5,
 spr_clubs_6,
 spr_clubs_7,
 spr_clubs_8,
 spr_clubs_9,
 spr_clubs_10,
 spr_clubs_jack,
 spr_clubs_queen, 
 spr_clubs_king,


 spr_card_back,
 spr_clubs_ace,
 spr_clubs_2,
 spr_clubs_3,
 spr_clubs_4,
 spr_clubs_5,
 spr_clubs_6,
 spr_clubs_7,
 spr_clubs_8,
 spr_clubs_9,
 spr_clubs_10,
 spr_clubs_jack,
 spr_clubs_queen,
 spr_clubs_king,

 spr_diamonds_ace,
 spr_diamonds_2,
 spr_diamonds_3,
 spr_diamonds_4,
 spr_diamonds_5,
 spr_diamonds_6,
 spr_diamonds_7,
 spr_diamonds_8,
 spr_diamonds_9,
 spr_diamonds_10,
 spr_diamonds_jack,
 spr_diamonds_queen,
 spr_diamonds_king,

 spr_hearts_ace,
 spr_hearts_2,
 spr_hearts_3,
 spr_hearts_4,
 spr_hearts_5,
 spr_hearts_6,
 spr_hearts_7,
 spr_hearts_8,
 spr_hearts_9,
 spr_hearts_10,
 spr_hearts_jack,
 spr_hearts_queen,
 spr_hearts_king,

 spr_spades_ace,
 spr_spades_2,
 spr_spades_3,
 spr_spades_4,
 spr_spades_5,
 spr_spades_6,
 spr_spades_7,
 spr_spades_8,
 spr_spades_9,
 spr_spades_10,
 spr_spades_jack,
 spr_spades_queen,
 spr_spades_king
 ];
}